/*
 * Tabela OFICIAL de códigos cClassTrib (IBS/CBS) e CST-IBS/CBS.
 *
 * FONTE: arquivo "cClassTrib 2026-06-22.xlsx", publicado pelo Portal Nacional
 * da NF-e em conjunto com a Receita Federal e o Comitê Gestor do IBS
 * (Informe Técnico 2025.002, planilhas "CST 2026-06-01 Pub" e
 * "cClass 2026-06-01 Pub"). Arquivo fornecido pelo usuário em 2026-09-12 e
 * transcrito integralmente (164 códigos cClassTrib e 18 códigos CST).
 *
 * Este arquivo é tratado como fonte de dados bruta/autoritativa — não edite
 * valores aqui para "consertar" algo; se um valor parecer errado, é a
 * própria tabela oficial que mudou e ela deve ser rebaixada de novo.
 *
 * Coluna "anexo": número arábico do Anexo da LC 214/2025 ao qual o código se
 * refere, quando a própria tabela oficial faz essa associação explícita no
 * campo "Nome cClassTrib" (ex.: "(Anexo I)"). Vazio quando não há Anexo
 * associado (regra geral de artigo, sem lista de NCMs).
 */
window.CCLASSTRIB_OFICIAL = {
  meta: {
    arquivo: "cClassTrib 2026-06-22.xlsx",
    planilhas: ["CST 2026-06-01 Pub", "cClass 2026-06-01 Pub"],
    fonte: "Portal Nacional da NF-e / Receita Federal / Comitê Gestor do IBS — Informe Técnico 2025.002",
    dataVersaoArquivo: "2026-06-22",
    dataImportacao: "2026-09-12",
    totalCodigosCClassTrib: 164
  },

  // As 18 situações de CST-IBS/CBS (planilha "CST 2026-06-01 Pub")
  cst: [
    { codigo: "000", descricao: "Tributação integral" },
    { codigo: "010", descricao: "Tributação com alíquotas uniformes" },
    { codigo: "011", descricao: "Tributação com alíquotas uniformes reduzidas" },
    { codigo: "200", descricao: "Alíquota reduzida" },
    { codigo: "220", descricao: "Alíquota fixa" },
    { codigo: "222", descricao: "Redução de base de cálculo" },
    { codigo: "221", descricao: "Alíquota fixa proporcional" },
    { codigo: "400", descricao: "Isenção" },
    { codigo: "410", descricao: "Imunidade e não incidência" },
    { codigo: "510", descricao: "Diferimento" },
    { codigo: "515", descricao: "Diferimento com redução de alíquota" },
    { codigo: "550", descricao: "Suspensão" },
    { codigo: "620", descricao: "Tributação monofásica" },
    { codigo: "800", descricao: "Transferência de crédito" },
    { codigo: "810", descricao: "Ajuste de IBS na ZFM" },
    { codigo: "811", descricao: "Ajustes" },
    { codigo: "820", descricao: "Tributação em documento específico" },
    { codigo: "830", descricao: "Exclusão de base de cálculo" }
  ],

  // As 164 hipóteses de cClassTrib (planilha "cClass 2026-06-01 Pub").
  // Campos: cst, codigo (cClassTrib), nome, artigo (LC 214/2025), tipoAliquota,
  // pRedIBS, pRedCBS (percentuais de redução), anexo (número arábico, se houver).
  codigos: [
    { cst: "000", codigo: "000001", nome: "Situações tributadas integralmente pelo IBS e CBS.", artigo: "", tipoAliquota: "Padrão", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "000", codigo: "000002", nome: "Exploração de via", artigo: "Art. 11, VIII", tipoAliquota: "Padrão", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "000", codigo: "000003", nome: "Regime automotivo - projetos incentivados (art. 311)", artigo: "Art. 311", tipoAliquota: "Padrão", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "000", codigo: "000004", nome: "Regime automotivo - projetos incentivados (art. 312)", artigo: "Art. 312", tipoAliquota: "Padrão", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "000", codigo: "000005", nome: "Operação com EAC destinado à mistura com gasolina A, mas com saída do biocombustível com destinação diversa", artigo: "Art. 179, I", tipoAliquota: "Padrão", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "010", codigo: "010001", nome: "Operações do FGTS não realizadas pela Caixa Econômica Federal", artigo: "Art. 212", tipoAliquota: "Uniforme setorial", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "010", codigo: "010002", nome: "Operações do serviço financeiro", artigo: "Art. 233", tipoAliquota: "Uniforme setorial", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "011", codigo: "011001", nome: "Planos de assistência funerária.", artigo: "Art. 236", tipoAliquota: "Uniforme nacional (referência)", pRedIBS: 60, pRedCBS: 60, anexo: null },
    { cst: "011", codigo: "011002", nome: "Planos de assistência à saúde", artigo: "Art. 237", tipoAliquota: "Uniforme nacional (referência)", pRedIBS: 60, pRedCBS: 60, anexo: null },
    { cst: "011", codigo: "011003", nome: "Intermediação de planos de assistência à saúde", artigo: "Art. 240", tipoAliquota: "Uniforme nacional (referência)", pRedIBS: 60, pRedCBS: 60, anexo: null },
    { cst: "011", codigo: "011004", nome: "Concursos e prognósticos", artigo: "Art. 246", tipoAliquota: "Uniforme nacional (referência)", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "011", codigo: "011005", nome: "Planos de assistência à saúde de animais domésticos", artigo: "Art. 243", tipoAliquota: "Uniforme nacional (referência)", pRedIBS: 30, pRedCBS: 30, anexo: null },
    { cst: "200", codigo: "200001", nome: "Serviços de transporte de bens até as zonas de processamento de exportação e bens exportados a partir das zonas de processamento de exportação", artigo: "Art. 103", tipoAliquota: "Padrão", pRedIBS: 100, pRedCBS: 100, anexo: null },
    { cst: "200", codigo: "200002", nome: "Fornecimento ou importação para produtor rural não contribuinte ou TAC", artigo: "Art. 110", tipoAliquota: "Padrão", pRedIBS: 100, pRedCBS: 100, anexo: null },
    { cst: "200", codigo: "200003", nome: "Vendas de produtos destinados à alimentação humana (Anexo I)", artigo: "Art. 125", tipoAliquota: "Padrão", pRedIBS: 100, pRedCBS: 100, anexo: 1 },
    { cst: "200", codigo: "200004", nome: "Fornecimento de dispositivos médicos (Anexo XII)", artigo: "Art. 144, I", tipoAliquota: "Padrão", pRedIBS: 100, pRedCBS: 100, anexo: 12 },
    { cst: "200", codigo: "200005", nome: "Fornecimento de dispositivos médicos para órgãos da administração pública e entidades de saúde imunes (Anexo IV)", artigo: "Art. 144, II", tipoAliquota: "Padrão", pRedIBS: 100, pRedCBS: 100, anexo: 4 },
    { cst: "200", codigo: "200006", nome: "Situação de emergência de saúde pública reconhecida pelo Poder público", artigo: "Art. 144, § 3º", tipoAliquota: "Padrão", pRedIBS: 100, pRedCBS: 100, anexo: null },
    { cst: "200", codigo: "200007", nome: "Fornecimento dos dispositivos de acessibilidade próprios para pessoas com deficiência (Anexo XIII)", artigo: "Art. 145, I", tipoAliquota: "Padrão", pRedIBS: 100, pRedCBS: 100, anexo: 13 },
    { cst: "200", codigo: "200008", nome: "Fornecimento dos dispositivos de acessibilidade próprios para pessoas com deficiência adquiridos por órgãos da administração pública (Anexo V)", artigo: "Art. 145, II", tipoAliquota: "Padrão", pRedIBS: 100, pRedCBS: 100, anexo: 5 },
    { cst: "200", codigo: "200009", nome: "Fornecimento dos medicamentos registrados na Anvisa", artigo: "Art. 146", tipoAliquota: "Padrão", pRedIBS: 100, pRedCBS: 100, anexo: null },
    { cst: "200", codigo: "200010", nome: "Fornecimento dos medicamentos registrados na Anvisa, adquiridos por órgãos da administração pública", artigo: "Art. 146, § 1º, I e II", tipoAliquota: "Padrão", pRedIBS: 100, pRedCBS: 100, anexo: null },
    { cst: "200", codigo: "200011", nome: "Fornecimento das composições para nutrição enteral e parenteral quando adquiridas por órgãos da administração pública (Anexo VI)", artigo: "Art. 146, § 2º", tipoAliquota: "Padrão", pRedIBS: 100, pRedCBS: 100, anexo: 6 },
    { cst: "200", codigo: "200012", nome: "Situação de emergência de saúde pública reconhecida pelo Poder público", artigo: "Art. 146, § 4º", tipoAliquota: "Padrão", pRedIBS: 100, pRedCBS: 100, anexo: null },
    { cst: "200", codigo: "200013", nome: "Fornecimento de tampões higiênicos, absorventes higiênicos internos ou externos", artigo: "Art. 147", tipoAliquota: "Padrão", pRedIBS: 100, pRedCBS: 100, anexo: null },
    { cst: "200", codigo: "200014", nome: "Fornecimento dos produtos hortícolas, frutas e ovos (Anexo XV)", artigo: "Art. 148", tipoAliquota: "Padrão", pRedIBS: 100, pRedCBS: 100, anexo: 15 },
    { cst: "200", codigo: "200015", nome: "Venda de automóveis de passageiros de fabricação nacional adquiridos por motoristas profissionais ou pessoas com deficiência", artigo: "Art. 149", tipoAliquota: "Padrão", pRedIBS: 100, pRedCBS: 100, anexo: null },
    { cst: "200", codigo: "200016", nome: "Prestação de serviços de pesquisa e desenvolvimento por Instituição Científica, Tecnológica e de Inovação (ICT)", artigo: "Art. 156", tipoAliquota: "Padrão", pRedIBS: 100, pRedCBS: 100, anexo: null },
    { cst: "200", codigo: "200017", nome: "Operações relacionadas ao FGTS", artigo: "Art. 212, § 3º, I", tipoAliquota: "Padrão", pRedIBS: 100, pRedCBS: 100, anexo: null },
    { cst: "200", codigo: "200018", nome: "Operações de resseguro e retrocessão", artigo: "Art. 223, § 4º", tipoAliquota: "Padrão", pRedIBS: 100, pRedCBS: 100, anexo: null },
    { cst: "200", codigo: "200019", nome: "Importador dos serviços financeiros contribuinte", artigo: "Art. 231, § 1º, II", tipoAliquota: "Padrão", pRedIBS: 100, pRedCBS: 100, anexo: null },
    { cst: "200", codigo: "200020", nome: "Operação praticada por sociedades cooperativas optantes por regime específico do IBS e CBS", artigo: "Art. 271", tipoAliquota: "Padrão", pRedIBS: 100, pRedCBS: 100, anexo: null },
    { cst: "200", codigo: "200021", nome: "Serviços de transporte público coletivo de passageiros ferroviário e hidroviário", artigo: "Art. 285, I", tipoAliquota: "Padrão", pRedIBS: 100, pRedCBS: 100, anexo: null },
    { cst: "200", codigo: "200022", nome: "Operação originada fora da ZFM que destine bem material industrializado a contribuinte estabelecido na ZFM", artigo: "Art. 445", tipoAliquota: "Padrão", pRedIBS: 100, pRedCBS: 100, anexo: null },
    { cst: "200", codigo: "200023", nome: "Operação realizada por indústria incentivada que destine bem material intermediário para outra indústria incentivada na ZFM", artigo: "Art. 448", tipoAliquota: "Padrão", pRedIBS: 100, pRedCBS: 100, anexo: null },
    { cst: "200", codigo: "200024", nome: "Operação originada fora das Áreas de Livre Comércio destinadas a contribuinte estabelecido nas Áreas de Livre Comércio", artigo: "Art. 463", tipoAliquota: "Padrão", pRedIBS: 100, pRedCBS: 100, anexo: null },
    { cst: "200", codigo: "200025", nome: "Fornecimento dos serviços de educação relacionados ao Programa Universidade para Todos (Prouni)", artigo: "Art. 308", tipoAliquota: "Padrão", pRedIBS: 60, pRedCBS: 100, anexo: null },
    { cst: "200", codigo: "200026", nome: "Locação de imóveis localizados nas zonas reabilitadas", artigo: "Art. 158, parágrafo único", tipoAliquota: "Padrão", pRedIBS: 80, pRedCBS: 80, anexo: null },
    { cst: "200", codigo: "200027", nome: "Operações de locação, cessão onerosa e arrendamento de bens imóveis", artigo: "Art. 261, parágrafo único", tipoAliquota: "Padrão", pRedIBS: 70, pRedCBS: 70, anexo: null },
    { cst: "200", codigo: "200028", nome: "Fornecimento dos serviços de educação (Anexo II)", artigo: "Art. 129", tipoAliquota: "Padrão", pRedIBS: 60, pRedCBS: 60, anexo: 2 },
    { cst: "200", codigo: "200029", nome: "Fornecimento dos serviços de saúde humana (Anexo III)", artigo: "Art. 130", tipoAliquota: "Padrão", pRedIBS: 60, pRedCBS: 60, anexo: 3 },
    { cst: "200", codigo: "200030", nome: "Venda dos dispositivos médicos (Anexo IV)", artigo: "Art. 131", tipoAliquota: "Padrão", pRedIBS: 60, pRedCBS: 60, anexo: 4 },
    { cst: "200", codigo: "200031", nome: "Fornecimento dos dispositivos de acessibilidade próprios para pessoas com deficiência (Anexo V)", artigo: "Art. 132", tipoAliquota: "Padrão", pRedIBS: 60, pRedCBS: 60, anexo: 5 },
    { cst: "200", codigo: "200032", nome: "Fornecimento dos medicamentos registrados na Anvisa ou produzidos por farmácias de manipulação, ressalvados os medicamentos sujeitos à alíquota zero", artigo: "Art. 133", tipoAliquota: "Padrão", pRedIBS: 60, pRedCBS: 60, anexo: null },
    { cst: "200", codigo: "200033", nome: "Fornecimento das composições para nutrição enteral e parenteral (Anexo VI)", artigo: "Art. 133, § 1º", tipoAliquota: "Padrão", pRedIBS: 60, pRedCBS: 60, anexo: 6 },
    { cst: "200", codigo: "200034", nome: "Fornecimento dos alimentos destinados ao consumo humano (Anexo VII)", artigo: "Art. 135", tipoAliquota: "Padrão", pRedIBS: 60, pRedCBS: 60, anexo: 7 },
    { cst: "200", codigo: "200035", nome: "Fornecimento dos produtos de higiene pessoal e limpeza (Anexo VIII)", artigo: "Art. 136", tipoAliquota: "Padrão", pRedIBS: 60, pRedCBS: 60, anexo: 8 },
    { cst: "200", codigo: "200036", nome: "Fornecimento de produtos agropecuários, aquícolas, pesqueiros, florestais e extrativistas vegetais in natura", artigo: "Art. 137", tipoAliquota: "Padrão", pRedIBS: 60, pRedCBS: 60, anexo: null },
    { cst: "200", codigo: "200037", nome: "Fornecimento de serviços ambientais de conservação ou recuperação da vegetação nativa", artigo: "Art. 137, § 3º", tipoAliquota: "Padrão", pRedIBS: 60, pRedCBS: 60, anexo: null },
    { cst: "200", codigo: "200038", nome: "Fornecimento dos insumos agropecuários e aquícolas (Anexo IX)", artigo: "Art. 138", tipoAliquota: "Padrão", pRedIBS: 60, pRedCBS: 60, anexo: 9 },
    { cst: "200", codigo: "200039", nome: "Fornecimento dos bens e serviços relacionados com produções nacionais artísticas, culturais, de eventos, jornalísticas e audiovisuais (Anexo X)", artigo: "Art. 139", tipoAliquota: "Padrão", pRedIBS: 60, pRedCBS: 60, anexo: 10 },
    { cst: "200", codigo: "200040", nome: "Fornecimento de serviços de comunicação institucional à administração pública", artigo: "Art. 140", tipoAliquota: "Padrão", pRedIBS: 60, pRedCBS: 60, anexo: null },
    { cst: "200", codigo: "200041", nome: "Fornecimento de serviço de educação desportiva (art. 141. I)", artigo: "Art. 141, I", tipoAliquota: "Padrão", pRedIBS: 60, pRedCBS: 60, anexo: null },
    { cst: "200", codigo: "200042", nome: "Fornecimento de serviço de gestão e exploração do desporto (art. 141. II)", artigo: "Art. 141, II", tipoAliquota: "Padrão", pRedIBS: 60, pRedCBS: 60, anexo: null },
    { cst: "200", codigo: "200043", nome: "Fornecimento à administração pública dos serviços e dos bens relativos à soberania (Anexo XI)", artigo: "Art. 142, I", tipoAliquota: "Padrão", pRedIBS: 60, pRedCBS: 60, anexo: 11 },
    { cst: "200", codigo: "200044", nome: "Operações e prestações de serviços de segurança da informação e segurança cibernética desenvolvidos por sociedade que tenha sócio brasileiro (Anexo XI)", artigo: "Art. 142, II", tipoAliquota: "Padrão", pRedIBS: 60, pRedCBS: 60, anexo: 11 },
    { cst: "200", codigo: "200045", nome: "Operações relacionadas a projetos de reabilitação urbana de zonas históricas e de áreas críticas de recuperação e reconversão urbanística", artigo: "Art. 158", tipoAliquota: "Padrão", pRedIBS: 60, pRedCBS: 60, anexo: null },
    { cst: "200", codigo: "200046", nome: "Operações com bens imóveis", artigo: "Art. 261", tipoAliquota: "Padrão", pRedIBS: 50, pRedCBS: 50, anexo: null },
    { cst: "200", codigo: "200047", nome: "Bares e Restaurantes", artigo: "Art. 275", tipoAliquota: "Padrão", pRedIBS: 40, pRedCBS: 40, anexo: null },
    { cst: "200", codigo: "200048", nome: "Hotelaria, Parques de Diversão e Parques Temáticos", artigo: "Art. 281", tipoAliquota: "Padrão", pRedIBS: 40, pRedCBS: 40, anexo: null },
    { cst: "200", codigo: "200049", nome: "Transporte coletivo de passageiros rodoviário, ferroviário e hidroviário", artigo: "Art. 286", tipoAliquota: "Padrão", pRedIBS: 40, pRedCBS: 40, anexo: null },
    { cst: "200", codigo: "200050", nome: "Serviços de transporte aéreo regional coletivo de passageiros ou de carga", artigo: "Art. 287", tipoAliquota: "Padrão", pRedIBS: 40, pRedCBS: 40, anexo: null },
    { cst: "200", codigo: "200051", nome: "Agências de Turismo", artigo: "Art. 289, II", tipoAliquota: "Padrão", pRedIBS: 40, pRedCBS: 40, anexo: null },
    { cst: "200", codigo: "200052", nome: "Prestação de serviços de profissões intelectuais", artigo: "Art. 127, I a XVIII", tipoAliquota: "Padrão", pRedIBS: 30, pRedCBS: 30, anexo: null },
    { cst: "200", codigo: "200053", nome: "Fornecimento de medicamentos registrados na Anvisa, quando classificados como soros ou vacinas", artigo: "Art. 146, § 1º, III", tipoAliquota: "Padrão", pRedIBS: 100, pRedCBS: 100, anexo: null },
    { cst: "200", codigo: "200054", nome: "Fornecimento de bem material pela cooperativa de produção agropecuária a associado não sujeito ao regime regular do IBS e da CBS", artigo: "Art. 271, § 1º, II", tipoAliquota: "Padrão", pRedIBS: 100, pRedCBS: 100, anexo: null },
    { cst: "220", codigo: "220001", nome: "Incorporação imobiliária submetida ao regime especial de tributação", artigo: "Art. 485, I", tipoAliquota: "Fixa", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "220", codigo: "220002", nome: "Incorporação imobiliária submetida ao regime especial de tributação", artigo: "Art. 485, II", tipoAliquota: "Fixa", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "220", codigo: "220003", nome: "Alienação de imóvel decorrente de parcelamento do solo", artigo: "Art. 486", tipoAliquota: "Fixa", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "221", codigo: "221001", nome: "Locação, cessão onerosa ou arrendamento de bem imóvel com alíquota sobre a receita bruta", artigo: "Art. 487, § 2º", tipoAliquota: "Fixa", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "221", codigo: "221002", nome: "Incorporação imobiliária submetida ao regime especial de tributação", artigo: "Art. 485, I", tipoAliquota: "Fixa", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "221", codigo: "221003", nome: "Incorporação imobiliária submetida ao regime especial de tributação", artigo: "Art. 485, II", tipoAliquota: "Fixa", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "221", codigo: "221004", nome: "Alienação de imóvel decorrente de parcelamento do solo", artigo: "Art. 486", tipoAliquota: "Fixa", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "222", codigo: "222001", nome: "Transporte internacional de passageiros, caso os trechos de ida e volta sejam vendidos em conjunto", artigo: "Art. 12 § 8º", tipoAliquota: "Padrão", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "400", codigo: "400001", nome: "Fornecimento de serviços de transporte público coletivo de passageiros rodoviário e metroviário", artigo: "Art. 157", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "400", codigo: "400002", nome: "Fornecimento de serviços de transporte público coletivo de passageiros rodoviário e metroviário com medição por quilômetro rodado", artigo: "Art. 157", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "410", codigo: "410001", nome: "Fornecimento de bonificações quando constem no documento fiscal e que não dependam de evento posterior", artigo: "Art. 5º, § 1º, I", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "410", codigo: "410002", nome: "Transferências entre estabelecimentos pertencentes ao mesmo contribuinte", artigo: "Art. 6º, II", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "410", codigo: "410003", nome: "Doações sem contraprestação em benefício do doador", artigo: "Art. 6º, VIII", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "410", codigo: "410004", nome: "Exportações de bens e serviços", artigo: "Art. 8º", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "410", codigo: "410005", nome: "Fornecimentos realizados pela União, pelos Estados, pelo Distrito Federal e pelos Municípios", artigo: "Art. 9º, I e § 1º", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "410", codigo: "410006", nome: "Fornecimentos realizados por entidades religiosas e templos de qualquer culto", artigo: "Art. 9º, II", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "410", codigo: "410007", nome: "Fornecimentos realizados por partidos políticos, entidades sindicais e instituições de educação e de assistência social", artigo: "Art. 9º, III", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "410", codigo: "410008", nome: "Fornecimentos de livros, jornais, periódicos e do papel destinado a sua impressão", artigo: "Art. 9º, IV", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "410", codigo: "410009", nome: "Fornecimentos de fonogramas e videofonogramas musicais produzidos no Brasil", artigo: "Art. 9º, V", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "410", codigo: "410010", nome: "Fornecimentos de serviço de comunicação nas modalidades de radiodifusão sonora e de sons e imagens de recepção livre e gratuita", artigo: "Art. 9º, VI", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "410", codigo: "410011", nome: "Fornecimentos de ouro, quando definido em lei como ativo financeiro ou instrumento cambial", artigo: "Art. 9º, VII", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "410", codigo: "410012", nome: "Fornecimento de condomínio edilício não optante pelo regime regular", artigo: "Art. 26, § 2º, II", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "410", codigo: "410013", nome: "Exportações de combustíveis", artigo: "Art. 98", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "410", codigo: "410014", nome: "Fornecimento de produtor rural não contribuinte", artigo: "Art. 164", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "410", codigo: "410015", nome: "Fornecimento por transportador autônomo não contribuinte", artigo: "Art. 169", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "410", codigo: "410016", nome: "Fornecimento ou aquisição de resíduos sólidos", artigo: "Art. 170", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "410", codigo: "410017", nome: "Aquisição de bem móvel com crédito presumido sob condição de revenda realizada", artigo: "Art. 171", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "410", codigo: "410018", nome: "Operações relacionadas aos fundos garantidores e executores de políticas públicas", artigo: "Art. 213", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "410", codigo: "410019", nome: "Exclusão da gorjeta na base de cálculo no fornecimento de alimentação", artigo: "Art. 274, I", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "410", codigo: "410020", nome: "Exclusão do valor de intermediação na base de cálculo no fornecimento de alimentação", artigo: "Art. 274, II", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "410", codigo: "410021", nome: "Contribuição de que trata o art. 149-A da Constituição Federal", artigo: "Art. 12 § 2º", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "410", codigo: "410022", nome: "Consolidação da propriedade do bem pelo credor", artigo: "Art. 200, I", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "410", codigo: "410023", nome: "Alienação de bens móveis ou imóveis que tenham sido objeto de garantia em que o prestador da garantia não seja contribuinte", artigo: "Art. 200, II, a", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "410", codigo: "410024", nome: "Consolidação da propriedade do bem pelo grupo de consórcio", artigo: "Art. 204, § 3º, I", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "410", codigo: "410025", nome: "Alienação de bem que tenha sido objeto de garantia em que o prestador da garantia não seja contribuinte", artigo: "Art. 204, § 3º II, a", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "410", codigo: "410026", nome: "Doação com anulação de crédito", artigo: "Art. 6º, § 2º II", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "410", codigo: "410027", nome: "Exportação de serviço ou de bem imaterial", artigo: "Art. 80 II", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "410", codigo: "410028", nome: "Operações com bens imóveis realizadas por pessoas físicas não consideradas contribuintes", artigo: "Art. 251, § 1º", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "410", codigo: "410029", nome: "Operações acobertadas somente pelo ICMS", artigo: "Art. 4º", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "410", codigo: "410030", nome: "Estorno de crédito por perecimento, deteriorização, roubo, furto ou extravio.", artigo: "Art. 47, § 6º", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "410", codigo: "410031", nome: "Fornecimento em período anterior ao início de vigência de incidências de CBS e IBS", artigo: "Art. 544, VI", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "410", codigo: "410032", nome: "Tributos incidentes na operação que não integram a base de cálculo do IBS e da CBS", artigo: "Art. 12, §2º V", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "410", codigo: "410033", nome: "Operações de Fundos de Investimento Imobiliário (FII) e Fundos de Investimento nas Cadeias Produtivas do Agronegócio (Fiagro)", artigo: "Art. 26, § 5º-A, I e II", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "410", codigo: "410034", nome: "Operações de fundos de investimento", artigo: "Art. 26, § 5º-A, III", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "410", codigo: "410035", nome: "Fornecimento realizado por nanoempreendedor", artigo: "Art. 26, IV", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "410", codigo: "410036", nome: "Descontos incondicionais", artigo: "Art. 12, §2º III", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "410", codigo: "410037", nome: "Importação os bens materiais sem incidência de IBS e CBS", artigo: "Art. 66, I,III e VII", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "410", codigo: "410999", nome: "Operações não onerosas sem previsão de tributação, não especificadas anteriormente", artigo: "Art. 4º, § 1º", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "510", codigo: "510001", nome: "Operações, sujeitas a diferimento, com energia elétrica, relativas à importação, geração, comercialização, distribuição e transmissão", artigo: "Art. 28, § 1º", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "515", codigo: "515001", nome: "Operações, sujeitas a diferimento, com insumos agropecuários e aquícolas (Anexo IX)", artigo: "Art. 138, § 2º", tipoAliquota: "Padrão", pRedIBS: 60, pRedCBS: 60, anexo: 9 },
    { cst: "550", codigo: "550001", nome: "Exportações de bens materiais", artigo: "Art. 82", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "550", codigo: "550002", nome: "Regime de Trânsito", artigo: "Art. 84", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "550", codigo: "550003", nome: "Regimes de Depósito (art. 85)", artigo: "Art. 85", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "550", codigo: "550004", nome: "Regimes de Depósito (art. 87)", artigo: "Art. 87", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "550", codigo: "550005", nome: "Regimes de Depósito (art. 87, Parágrafo único)", artigo: "Art. 87, parágrafo único", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "550", codigo: "550006", nome: "Regimes de Permanência Temporária", artigo: "Art. 88", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "550", codigo: "550007", nome: "Regimes de Aperfeiçoamento", artigo: "Art. 90", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "550", codigo: "550008", nome: "Importação de bens para o Regime de Repetro-Temporário", artigo: "Art. 93, I", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "550", codigo: "550009", nome: "GNL-Temporário", artigo: "Art. 93, II", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "550", codigo: "550010", nome: "Repetro-Permanente", artigo: "Art. 93, III", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "550", codigo: "550011", nome: "Repetro-Industrialização", artigo: "Art. 93, IV", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "550", codigo: "550012", nome: "Repetro-Nacional", artigo: "Art. 93, V", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "550", codigo: "550013", nome: "Repetro-Entreposto", artigo: "Art. 93, VI", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "550", codigo: "550014", nome: "Zona de Processamento de Exportação", artigo: "Arts. 99, 100 e 102", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "550", codigo: "550015", nome: "Regime Tributário para Incentivo à Modernização e à Ampliação da Estrutura Portuária", artigo: "Art. 105", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "550", codigo: "550016", nome: "Regime Especial de Incentivos para o Desenvolvimento da Infraestrutura", artigo: "Art. 106", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "550", codigo: "550017", nome: "Regime Tributário para Incentivo à Atividade Naval - Renaval (Art. 107, I)", artigo: "Art. 107, I", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "550", codigo: "550018", nome: "Desoneração da aquisição de bens de capital", artigo: "Art. 109", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "550", codigo: "550019", nome: "Importação de bem material por indústria incentivada para utilização na ZFM", artigo: "Art. 443", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "550", codigo: "550020", nome: "Áreas de livre comércio", artigo: "Art. 461", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "550", codigo: "550021", nome: "Industrialização destinada a exportações", artigo: "Art. 82, § 11", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "550", codigo: "550022", nome: "Regime Especial de Incentivos para a Produção de Hidrogênio de Baixa Emissão de Carbono (Rehidro)", artigo: "Art. 106, § 7º", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "550", codigo: "550023", nome: "Operações com hidrocarbonetos líquidos derivados de petróleo não combustíveis ou de gás natural, inclusive nafta", artigo: "Art. 172, § 2º", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "550", codigo: "550024", nome: "Regime Tributário para Incentivo à Atividade Naval - Renaval (Art. 107, II)", artigo: "Art. 107, II", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "550", codigo: "550025", nome: "Regime Tributário para Incentivo à Atividade Naval - Renaval (Art. 107, III)", artigo: "Art. 107, III", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "620", codigo: "620001", nome: "Tributação monofásica sobre combustíveis", artigo: "Art. 172", tipoAliquota: "Uniforme setorial", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "620", codigo: "620002", nome: "Tributação monofásica com responsabilidade pela retenção sobre combustíveis", artigo: "Art. 178", tipoAliquota: "Uniforme setorial", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "620", codigo: "620003", nome: "Tributação monofásica com responsabilidade de retenção de tributos por terceiros", artigo: "Art. 178", tipoAliquota: "Uniforme setorial", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "620", codigo: "620004", nome: "Tributação monofásica sobre mistura de EAC com gasolina A em percentual superior ao obrigatório", artigo: "Art. 179, II, a", tipoAliquota: "Uniforme setorial", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "620", codigo: "620005", nome: "Tributação monofásica sobre mistura de EAC com gasolina A em percentual inferior ao obrigatório", artigo: "Art. 179, II, b", tipoAliquota: "Uniforme setorial", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "620", codigo: "620006", nome: "Tributação monofásica sobre combustíveis cobrada anteriormente", artigo: "Art. 180", tipoAliquota: "Uniforme setorial", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "620", codigo: "620007", nome: "Perecimento, deteriorização, roubo, furto ou extravio no regime monofásico", artigo: "Art. 47, § 6º", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "800", codigo: "800001", nome: "Fusão, cisão ou incorporação", artigo: "Art. 55", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "800", codigo: "800002", nome: "Transferência de crédito do associado, inclusive as cooperativas singulares", artigo: "Art. 272", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "810", codigo: "810001", nome: "Crédito presumido de IBS sobre o valor apurado nos fornecimentos a partir da ZFM", artigo: "Art. 450, § 1º", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "811", codigo: "811001", nome: "Anulação de Crédito por Saídas Imunes/Isentas", artigo: "Art. 51", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "811", codigo: "811002", nome: "Débitos de notas fiscais não processadas na apuração", artigo: "Art. 45", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "811", codigo: "811003", nome: "Desenquadramento do Simples Nacional", artigo: "Art. 41", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "820", codigo: "820001", nome: "Documento com informações de fornecimento de serviços de planos de assistência à saúde elencados no art. 234 da Lei Complementar nº 214, de 2025", artigo: "Art. 234", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "820", codigo: "820002", nome: "Documento com informações de fornecimento de serviços de planos de assistência funerária", artigo: "Art. 236", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "820", codigo: "820003", nome: "Documento com informações de fornecimento de serviços de planos de assistência à saúde de animais domésticos", artigo: "Art. 243", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "820", codigo: "820004", nome: "Documento com informações de prestação de serviços de consursos de prognósticos", artigo: "Art. 248", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "820", codigo: "820005", nome: "Documento com informações de alienação de bens imóveis", artigo: "Art. 254, § 1º", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "820", codigo: "820006", nome: "Documento com informações de fornecimento de serviços de exploração de via", artigo: "Art. 11, VIII", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "820", codigo: "820007", nome: "Documento com informações de fornecimento de serviços financeiros", artigo: "Art. 181", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "820", codigo: "820008", nome: "Documento com informações de fornecimento de serviço continuado, mas com tributação realizada em fatura anterior", artigo: "Art. 10, § 3º", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "820", codigo: "820009", nome: "Cobrança relativa a fornecimentos declarados em outro documento", artigo: "Art. 60", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null },
    { cst: "830", codigo: "830001", nome: "Documento com exclusão da BC da CBS e do IBS de energia elétrica fornecida pela distribuidora à UC", artigo: "Art. 28, parágrafos 3° e 4°", tipoAliquota: "Sem alíquota", pRedIBS: 0, pRedCBS: 0, anexo: null }
  ]
};
